spring:
  datasource:
    url: jdbc:postgresql://localhost:5420/postgres
    username: postgres
    password: sanchez
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: beca-service
  profiles:
    active: dev

server:
  port: 9091

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://gatewayservice:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
