Ext.define('App.view.alumno.AlumnoGrid',{
    extend:'Ext.container.Container',
    style:'padding:10px',
    layout:'vbox',
    items:[{
        xtype: 'gridpanel',
        width: 400,
        height: 200,
        title:'Lista de alumnos',
        store:'AlumnoStore',
        collapsible:true,
        columns:[{
            text:'IdeAlu',
            hidden:true,
            dataIndex:'ideAlu'
        },{
            text:'DNI',
            sortable:true,
            dataIndex:'nroDni',
            flex:3
        },{
            text:'Paterno',
            sortable:true,
            dataIndex:'apePat',
            flex:3
        },{
            text:'Materno',
            sortable:true,
            dataIndex:'apeMat',
            flex:3
        },{
            text:'Nombres',
            sortable:true,
            dataIndex:'desNom',
            flex:3
        },{
            text:'Nacimiento',
            sortable:true,
            dataIndex:'fchNac',
            flex:3
        }],
        selType:'rowmodel',
        dockedItems:[{
            xtype:'pagingtoolbar',
            store:'AlumnoStore',
            dock:'bottom',
            displayInfo:true
        }]
    }]
});